name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: UnitTests
    runs-on: ubuntu-latest
    strategy:
      matrix:
         ruby-version: [ '2.4', '2.3', '2.2' ,'2.1' , '2.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Dependencies Installation
        run: |
          bundle install --without development
      - name: Run Tests
        run: |
          ruby --version
          bundle exec rake
